apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "55 2 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: database-backup
              persistentVolumeClaim:
                claimName: database-backup
          containers:
            - name: database-backup
              image: 'registry.access.redhat.com/rhscl/mariadb-101-rhel7:10.1'
              command:
                - 'bash'
                - '-eo'
                - 'pipefail'
                - '-c'
                - >
                  trap "echo Backup failed; exit 0" ERR;
                  FILENAME=backup-${DATABASE_NAME}-`date +%Y-%m-%d_%H%M%S`.sql.gz;
                  time (find /database-backup -type f -name "backup-${DATABASE_NAME}-*"  -exec ls -1tr "{}" + | head -n -${DATABASE_BACKUP_KEEP} | xargs rm -fr;
                  mysqldump -u$DATABASE_USER -p$DATABASE_PASSWORD -h$DATABASE_HOST -P$DATABASE_PORT --skip-lock-tables --quick --routines --all-databases | gzip > /database-backup/$FILENAME);
                  echo "";
                  echo "Backup successful"; du -h /database-backup/$FILENAME;
                  echo "to restore the backup to the serviced host use: $ mysql -u$DATABASE_USER -p$DATABASE_PASSWORD -h$DATABASE_HOST < /database-backup/<backupfile> (unpacked)"
              env:
                - name: DATABASE_USER
                  value: root
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                       key: database-root-password
                       name: mariadb
                - name: DATABASE_BACKUP_KEEP
                  value: "5"
                - name: DATABASE_SECRET
                  value: mariadb 
                - name: DATABASE_HOST
                  value: mariadb
                - name: DATABASE_PORT
                  value: "3306"
                - name: DATABASE_NAME
                  value: OTAcluster
                - name: TZ
                  value: Europe/Amsterdam
              volumeMounts:
                - name: database-backup
                  mountPath: /database-backup
          restartPolicy: Never
