apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-backup
  namespace: mariadb-bb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
